### ISSUE TITLE
Is there an up-to-date version of this generator somewhere?

### ISSUE THREAD

**Issue by own3mall** [ozguruysal/b3-config-generator#19]
https://github.com/BigBrotherBot/big-brother-bot/issues/433

I think this version is missing the iourt43 parser option?  Not sure if it's missing anything else since b3 was last updated...

**Comment by ozguruysal** [comment]
I haven't been involved in the project for a long time and not sure what's missing. Feel free to send a PR if you want.

**Comment by ozguruysal** [comment]
Fixed in #20
